Hotel.WebPortal/Hotel.WebPortal/Models/ErrorViewModel.cs
namespace Hotel.WebPortal.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Hotel.WebPortal/Hotel.WebPortal/Controllers/EventController.cs
using Microsoft.AspNetCore.Mvc;

namespace Hotel.WebPortal.Controllers
{
    public class EventController : Controller
    {

        public IActionResult Index()
        {
            return View();
        }
    }
}

Hotel.WebPortal/Hotel.WebPortal/Controllers/HomeController.cs
using Hotel.WebPortal.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Hotel.WebPortal.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }
        public IActionResult Contact()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Hotel.WebPortal/Hotel.WebPortal/Controllers/LocationController.cs
using Microsoft.AspNetCore.Mvc;

namespace Hotel.WebPortal.Controllers
{
    public class LocationController : Controller
    {
  
        public IActionResult Index()
        {
            return View();
        }
    }
}

Hotel.WebPortal/Hotel.WebPortal/Controllers/RoomController.cs
using Microsoft.AspNetCore.Mvc;

namespace Hotel.WebPortal.Controllers
{
    public class RoomController : Controller
    {
        private IWebHostEnvironment host;
        public RoomController(IWebHostEnvironment host)
        {
            this.host = host;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Details()
        {
            return View();
        }

        public IActionResult List()
        {
            return View();
        }

        [HttpPost]

        public IActionResult SubscribeClient(IFormFile userFile)
        {
            string path = Path.Combine(host.WebRootPath,"UserFiles", userFile.FileName);
            using (var stream = new FileStream(path, FileMode.Create))
            {
                userFile.CopyTo(stream);
            }

            return View();
        }


    }
}

Hotel.WebPortal/Hotel.WebPortal/Controllers/TeamController.cs
using Microsoft.AspNetCore.Mvc;

namespace Hotel.WebPortal.Controllers
{
    public class TeamController : Controller
    {

        public IActionResult Index()
        {
            return View();
        }
    }
}

Hotel.WebPortal/Hotel.WebPortal/Views/Event/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<!-- Breadcrumb Area Start-->
<section class="breadcrumb-area overlay-dark-2 bg-3">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="breadcrumb-text text-center">
                    <h2>Events</h2>
                    <p>A quality room of hotel ATR with sea or mountain view</p>
                    <div class="breadcrumb-bar">
                        <ul class="breadcrumb">
                            <li><a href="index.html">Home</a></li>
                            <li>Events</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Breadcrumb Area End -->
<!-- Event Area Start -->
<section class="event-area pt-90">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="section-title text-center">
                    <h3>upcoming events</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellente sque vel volutpat felis, eu condimentum massa. Pellentesque mollis eros vel mattis tempor. Aliquam </p>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="event-menu">
                    <button data-filter="*" class="active"> All</button>
                    <button data-filter=".music">Music Party</button>
                    <button data-filter=".birthday">Birthday Party</button>
                    <button data-filter=".conference">Conference</button>
                    <button data-filter=".wedding">Wedding Party</button>
                    <button data-filter=".photography">Photography Party</button>
                </div>
            </div>
        </div>
        <div class="row event-items">
            <div class="single-event col-md-8 col-sm-8 col-xs-12 conference">
                <div class="single-event-item">
                    <img src="img/event/1.jpg" alt="">
                    <div class="event-text">
                        <h3 class="event-title">management conferences</h3>
                        <h3 class="author-name">By : Jhtyg Hyuir</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt</p>
                    </div>
                </div>
            </div>
            <div class="single-event col-md-4 small col-sm-4 col-xs-12 music">
                <div class="single-event-item">
                    <img src="img/event/2.jpg" alt="">
                    <div class="event-text">
                        <h3 class="event-title">Music Concert</h3>
                        <h3 class="author-name">By : Jhon Doe</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt</p>
                    </div>
                </div>
            </div>
            <div class="single-event col-md-4 small col-sm-4 col-xs-12 birthday">
                <div class="single-event-item">
                    <img src="img/event/3.jpg" alt="">
                    <div class="event-text">
                        <h3 class="event-title">birthday party</h3>
                        <h3 class="author-name">By : Marry Luis</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt</p>
                    </div>
                </div>
            </div>
            <div class="single-event col-md-8 col-sm-8 col-xs-12 wedding">
                <div class="single-event-item">
                    <img src="img/event/4.jpg" alt="">
                    <div class="event-text">
                        <h3 class="event-title">weeding party </h3>
                        <h3 class="author-name">By : Kathy Luis</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt</p>
                    </div>
                </div>
            </div>
            <div class="single-event col-md-8 col-sm-8 col-xs-12 photography">
                <div class="single-event-item">
                    <img src="img/event/5.jpg" alt="">
                    <div class="event-text">
                        <h3 class="event-title">management conferences</h3>
                        <h3 class="author-name">By : Dan Brown</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt</p>
                    </div>
                </div>
            </div>
            <div class="single-event col-md-4 small col-sm-4 col-xs-12 photography">
                <div class="single-event-item">
                    <img src="img/event/6.jpg" alt="">
                    <div class="event-text">
                        <h3 class="event-title">photography</h3>
                        <h3 class="author-name">By : Khaled Hossaini</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Event Area End -->
<!-- Client Area Start -->
<div class="client-area">
    <div class="container">
        <div class="row">
            <div class="client-carousel">
                <div class="single-client">
                    <div class="client-image">
                        <a href="#">
                            <img src="img/client/1.png" alt="" class="p-img">
                            <img src="img/client/1-hover.png" alt="" class="s-img">
                        </a>
                    </div>
                </div>
                <div class="single-client">
                    <div class="client-image">
                        <a href="#">
                            <img src="img/client/2.png" alt="" class="p-img">
                            <img src="img/client/2-hover.png" alt="" class="s-img">
                        </a>
                    </div>
                </div>
                <div class="single-client">
                    <div class="client-image">
                        <a href="#">
                            <img src="img/client/3.png" alt="" class="p-img">
                            <img src="img/client/3-hover.png" alt="" class="s-img">
                        </a>
                    </div>
                </div>
                <div class="single-client">
                    <div class="client-image">
                        <a href="#">
                            <img src="img/client/4.png" alt="" class="p-img">
                            <img src="img/client/4-hover.png" alt="" class="s-img">
                        </a>
                    </div>
                </div>
                <div class="single-client">
                    <div class="client-image">
                        <a href="#">
                            <img src="img/client/5.png" alt="" class="p-img">
                            <img src="img/client/5-hover.png" alt="" class="s-img">
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Client Area End -->
<!-- Newsletter Area Start -->
<section class="newsletter-area bg-light">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-sm-12 col-xs-12">
                <div class="newsletter-container">
                    <h3>NewsLetter Sign-Up</h3>
                    <div class="newsletter-form">
                        <form action="#" id="mc-form" class="mc-form fix">
                            <input id="mc-email" type="email" name="email" placeholder="Enter your E-mail">
                            <button id="mc-submit" type="submit" class="default-btn">subcribes</button>
                        </form>
                        <!-- mailchimp-alerts Start -->
                        <div class="mailchimp-alerts">
                            <div class="mailchimp-submitting"></div><!-- mailchimp-submitting end -->
                            <div class="mailchimp-success"></div><!-- mailchimp-success end -->
                            <div class="mailchimp-error"></div><!-- mailchimp-error end -->
                        </div>
                        <!-- mailchimp-alerts end -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Newsletter Area End -->

Hotel.WebPortal/Hotel.WebPortal/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    Layout = "_HomeLayout";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Hotel.WebPortal/Hotel.WebPortal/Views/Shared/_HomeLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Home Page || Hotel ATR</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Favicon Icon -->
    <link rel="shortcut icon" type="~/image/x-icon" href="img/favicon.ico">

    <!-- All css here -->
    <link rel="stylesheet" href="~/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/shortcode/shortcodes.css">
    <link rel="stylesheet" href="~/style.css">
    <link rel="stylesheet" href="css/responsive.css">
    <script src="~/js/vendor/modernizr-2.8.3.min.js"></script>
</head>
<body>
    <!--[if lt IE 8]>
        <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->
    <!-- Header Area Start -->
    <header class="header-area fixed header-sticky">
        <div class="container">
            <div class="row">
                <div class="col-lg-5 col-md-4 col-sm-4 col-xs-12">
                    <div class="logo">
                        <a asp-action="Index" asp-controller="Home"><img src="~/img/logo/logo.png" alt="HotelATR"></a>
                    </div>
                </div>
                <div class="col-lg-7 col-md-8 col-sm-8 hidden-xs">
                    <div class="header-top fix">
                        <div class="header-contact">
                            <span class="text-theme">Contact:</span>
                            <span>0088-234-675-827</span>
                        </div>
                        <div class="header-links">
                            <a href="https://www.facebook.com/"><i class="zmdi zmdi-facebook"></i></a>
                            <a href="https://twitter.com/"><i class="zmdi zmdi-twitter"></i></a>
                            <a href="https://plus.google.com/"><i class="zmdi zmdi-google-plus"></i></a>
                            <a href="https://www.instagram.com/"><i class="zmdi zmdi-instagram"></i></a>
                            <a href="https://www.pinterest.com/"><i class="zmdi zmdi-pinterest"></i></a>
                        </div>
                    </div>
                    <!-- Mainmenu Start -->
                    <div class="main-menu hidden-xs">
                        <nav>
                            @{
                                Html.RenderPartial("_MainMenu");
                            }
                        </nav>
                    </div>
                    <!-- Mainmenu End -->
                </div>
            </div>
        </div>
        <!-- Mobile Menu Area start -->
        <div class="mobile-menu-area">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12">
                        <div class="mobile-menu">
                            <nav id="dropdown">
                                @{
                                    Html.RenderPartial("_MobileMenu");
                                }
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Mobile Menu Area end -->
    </header>
    <!-- Header Area End -->
    <!-- Background Area Start -->
    <section class="slider-area">
        <div class="slider-wrapper">
            <div class="single-slide" style="background-image: url('img/slider/1.jpg');">
                <div class="banner-content overlay">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-10 col-md-offset-1">
                                <div class="text-content-wrapper">
                                    <div class="text-content text-center">
                                        <h1 class="pt-180">welcome to hotel atr</h1>
                                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
                                        <div class="banner-btn">
                                            <a class="default-btn" href="room-grid.html">explore</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="single-slide" style="background-image: url('img/slider/2.jpg');">
                <div class="banner-content overlay">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-10 col-md-offset-1">
                                <div class="text-content-wrapper slide-two">
                                    <div class="text-content text-center">
                                        <h1 class="pt-180">welcome to hotel atr</h1>
                                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
                                        <div class="banner-btn">
                                            <a class="default-btn" href="room-grid.html">explore</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Background Area End -->
    
    @RenderBody()


    <!-- Footer Area Start -->
    <footer class="footer-area">
        <!-- Footer Widget Start -->
        <div class="footer-widget-area bg-dark">
            <div class="container">
                <div class="row">
                    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                        <div class="single-footer-widget">
                            <div class="footer-logo">
                                <a asp-action="Index" asp-controller="Home"><img src="~/img/logo/footer-logo.png" alt="HotelATR"></a>
                            </div>
                            <p>Lorem ipsum dolor sit amet, conse acteir our adipisicing elit, sed do eiusmod the a tempor the incididunt ut labore et dolore magnaa liqua. Ut enim minimn.</p>
                            <div class="social-icons">
                                <a href="https://www.facebook.com/"><i class="zmdi zmdi-facebook"></i></a>
                                <a href="https://www.instagram.com/"><i class="zmdi zmdi-instagram"></i></a>
                                <a href="https://www.rss.com/"><i class="zmdi zmdi-rss"></i></a>
                                <a href="https://twitter.com/"><i class="zmdi zmdi-twitter"></i></a>
                                <a href="https://www.pinterest.com/"><i class="zmdi zmdi-pinterest"></i></a>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                        <div class="single-footer-widget">
                            <h3>contact us</h3>
                            <div class="c-info">
                                <span><i class="zmdi zmdi-pin"></i></span>
                                <span>House No 27, Road No 07,<br>East Road, Dhaka, Bangladesh</span>
                            </div>
                            <div class="c-info">
                                <span><i class="zmdi zmdi-email"></i></span>
                                <span>devitems@gmail.com<br>support@devitems.com</span>
                            </div>
                            <div class="c-info">
                                <span><i class="zmdi zmdi-phone"></i></span>
                                <span>+660 256 24857<br>+660 256 24857</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-2 hidden-md hidden-sm col-xs-12">
                        <div class="single-footer-widget">
                            <h3>quick links</h3>
                            <ul class="footer-list">
                                <li><a asp-action="Index" asp-controller="Home">Home</a></li>
                                <li><a asp-action="Index" asp-controller="Team">Stuffs</a></li>
                                <li><a href="room-grid.html">Suits &amp; Rooms</a></li>
                                <li>@Html.ActionLink("EVENT","Index", "Event")</li>
                                <li>@Html.ActionLink("LOCATION","Index", "Location")</li>
                                <li><a asp-action="Contact" asp-controller="Home">Contact</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                        <div class="single-footer-widget">
                            <h3>collections</h3>
                            <div class="instagram-image">
                                <div class="footer-img">
                                    <a href="room-grid.html"><img src="img/footer/1.jpg" alt=""></a>
                                </div>
                                <div class="footer-img">
                                    <a href="room-grid.html"><img src="img/footer/2.jpg" alt=""></a>
                                </div>
                                <div class="footer-img">
                                    <a href="room-grid.html"><img src="img/footer/3.jpg" alt=""></a>
                                </div>
                                <div class="footer-img">
                                    <a href="room-grid.html"><img src="img/footer/4.jpg" alt=""></a>
                                </div>
                                <div class="footer-img">
                                    <a href="room-grid.html"><img src="img/footer/5.jpg" alt=""></a>
                                </div>
                                <div class="footer-img">
                                    <a href="room-grid.html"><img src="img/footer/6.jpg" alt=""></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer Widget End -->
        <!-- Footer Bottom Area Start -->
        <div class="footer-bottom-area bg-black">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="footer-text text-center">
                            <span>Copyright © 2017 <a href="#">Hastech</a> All Right Reserved.</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer Bottom Area End -->
    </footer>
    <!-- Footer Area End -->


    <!-- All js here -->
    <script src="~/js/vendor/jquery-1.12.4.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/owl.carousel.min.js"></script>
    <script src="~/js/ajax-mail.js"></script>
    <script src="~/js/jquery.ajaxchimp.min.js"></script>
    <script src="~/js/jquery.meanmenu.js"></script>
    <script src="~/js/jquery.counterup.min.js"></script>
    <script src="~/js/waypoints.min.js"></script>
    <script src="~/js/isotope.pkgd.min.js"></script>
    <script src="~/js/imagesloaded.pkgd.min.js"></script>
    <script src="~/js/jquery.magnific-popup.js"></script>
    <script src="~/js/plugins.js"></script>
    <script src="~/js/main.js"></script>
</body>
</html>

Hotel.WebPortal/Hotel.WebPortal/Views/Shared/_MainMenu.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<ul>
    <li><a asp-action="Index" asp-controller="Home">HOME</a></li>
    <li>
        <a href="@Url.Action("Index", "Room")">ROOMS</a>
        <ul class="submenu">
            <li>@Html.ActionLink("ROOM LIST","List", "Room")</li>
            <li>@Html.ActionLink("ROOM DETAILS","Details", "Room")</li>
        </ul>
    </li>
    <li>
        <a href="#">ACTIVITIES</a>
        <ul class="submenu megamenu">
            <li>
                <a href="#">Megamenu List</a>
                <ul>
                    <li>@Html.ActionLink("Location","Index", "Location")</li>
                    <li><a href="room-grid.html">Room Grid</a></li>
                    <li><a href="room-list.html">Room List</a></li>
                    <li><a href="room-details.html">Room Details</a></li>
                    <li><a href="#">Mega menu</a></li>
                </ul>
            </li>
            <li>
                <a href="#">Megamenu List</a>
                <ul>
                    <li><a href="event.html">Event</a></li>
                    <li><a href="#">Mega menu</a></li>
                    <li><a href="contact.html">Contact</a></li>
                    <li><a href="team.html">Team</a></li>
                    <li><a href="#">Mega menu</a></li>
                </ul>
            </li>
            <li>
                <a href="#">Megamenu List</a>
                <ul>
                    <li>@Html.ActionLink("ROOM LIST","List", "Room")</li>
                    <li><a href="#">Mega menu</a></li>
                    <li><a href="room-grid.html">Room Grid</a></li>
                    <li><a href="room-details.html">Room Details</a></li>
                    <li><a href="#">Mega menu</a></li>
                </ul>
            </li>
        </ul>
    </li>
    <li>@Html.ActionLink("LOCATION","Index", "Location")</li>
    <li>@Html.ActionLink("EVENT","Index", "Event")</li>
    <li>@Html.ActionLink("TEAM","Index", "Team")</li>
    <li><a asp-action="Contact" asp-controller="Home">CONTACT</a></li>
</ul>

Hotel.WebPortal/Hotel.WebPortal/Views/Shared/_MobileMenu.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<ul>
    <li><a href="index.html">HOME</a></li>
    <li>
        <a href="room-grid.html">ROOMS</a>
        <ul class="submenu">
            <li><a href="room-list.html">ROOM LIST</a></li>
            <li><a href="room-details.html">ROOM DETAILS</a></li>
        </ul>
    </li>
    <li><a href="location.html">LOCATION</a></li>
    <li><a href="event.html">EVENT</a></li>
    <li><a href="team.html">TEAM</a></li>
    <li><a href="contact.html">CONTACT</a></li>
</ul>